### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by FranSS7** [LazyNeil/liebre#1]
- [x] 1 - Respecto a la estructura del sitio visualizar que contenga estos elementos cada
sección.
- [x] 2 -  Haciendo foco en los estilos del pie de página.
- [x] 3 - El sitio se adapta a distintas resoluciones de pantalla.
- [x] 4 - El sitio cuenta con un formulario de registro de usuarios
- [x] 5 - ¿El sitio cuenta con un formulario de login?
- [x] 6 - ¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios?
- [x] 7 - ¿El search bar es un formulario?
- [x] 8 - ¿Se utilizan animaciones y propiedades de transición de CSS?
 - 9  Buen diseño e implementación de las consiganas
- 10 Deberia agregar un readme en el repositorio

**Comment by LazyNeil** [comment]
Resuelto en el commit #2a67a1
